main: com.cavetale.sidebar.SidebarPlugin
name: Sidebar

version: 0.1
api-version: '1.20'

description: Provide a per-player sidebar for plugins to display messages in.
author: StarTux
website: https://github.com/StarTux/Sidebar

depend: [Core]
softdepend: []

commands:

  sidebar:
    aliases: []
    description: User interface
    permission: sidebar.sidebar
    usage: |-
      /sidebar toggle - Turn display on/off
      /sidebar on - Turn display on
      /sidebar off - Turn display off

  sidebaradmin:
    aliases: [sidebaradm]
    description: Admin interface
    permission: sidebar.admin
    usage: |-
      /sidebaradmin

permissions:

  sidebar.sidebar:
    description: Use /sidebar
    default: op

  sidebar.admin:
    description: Use /sidebaradmin
    default: op
